name: pack

on: [push]

jobs:
    pack:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and pack app
              run: |
                  npm ci
                  npm run release
              env:
                  CI: true
            - uses: actions/upload-artifact@v3
              with:
                  name: ave-react-app
                  path: "bin"
                  if-no-files-found: error
